# These are supported funding model platforms

github: # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [laff, Airbnb]
patreon: # Replace with a single Patreon username smithla
open_collective: # Replace with a single Open Collective username voodoo.io
ko_fi: # Replace with a single Ko-fi username Mia
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: # Replace with a single Community Bridge project-name e.g., slack-foundry
liberapay: # Replace with a single Liberapay username bic
issuehunt: # Replace with a single IssueHunt username uso
otechie: # Replace with a single Otechie username tango
custom: # Replace with up to 4 custom sponsorship URLs e.g., ['https://forddaily.net','https://NAACP.org','https://nfl.com']
